# Generated by Django 2.0.13 on 2019-04-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created_date', models.DateField(default='2019-04-07')),
                ('due_date', models.DateField(default='2019-04-07')),
            ],
        ),
    ]
